name: Run Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install pnpm -g
      - run: pnpm install
      - run: pnpm build
      - run: pnpm format:check
      - run: pnpm test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: vitest-report
          path: vitest-report
